Feature: Timezone Retrieval
As an API user,
I want to be able to interact with the timezone data,
So that I can retrieve all timezones, request specific timezone information, and receive proper error handling for invalid timezone requests.

    Scenario: Request one valid timezone should return one timezone
        Given I have a request to get 'America/New_York' timezone
        When I send the request
        Then the response should return '200' status code
        Then the response should contain timezone information:
          | Name                         | Offset |
          | (UTC-05:00) America/New_York | -5     |

    Scenario: Request one invalid timezone should return 404
        Given I have a request to get 'invalid-timezone' timezone
        When I send the request
        Then the response should return '404' status code

    # This test is expected to fail if a timezone is changed, removed or added
    Scenario: Retrieving all timezones should return exactly 419 timezones
        Given I have a request to get all timezones
        When I send the request
        Then the response should return '200' status code
        # As of 14th of January 2026, there are 419 timezones.
        Then I should get exactly 419 timezones
        And the list of timezone response should be:
          | Name                                       | Offset    | Id                             |
          | (UTC-11:00) Pacific/Midway                 | -11:00:00 | Pacific/Midway                 |
          | (UTC-11:00) Pacific/Niue                   | -11:00:00 | Pacific/Niue                   |
          | (UTC-11:00) Pacific/Pago_Pago              | -11:00:00 | Pacific/Pago_Pago              |
          | (UTC-10:00) America/Adak                   | -10:00:00 | America/Adak                   |
          | (UTC-10:00) Pacific/Honolulu               | -10:00:00 | Pacific/Honolulu               |
          | (UTC-10:00) Pacific/Rarotonga              | -10:00:00 | Pacific/Rarotonga              |
          | (UTC-10:00) Pacific/Tahiti                 | -10:00:00 | Pacific/Tahiti                 |
          | (UTC-09:30) Pacific/Marquesas              | -09:30:00 | Pacific/Marquesas              |
          | (UTC-09:00) America/Anchorage              | -09:00:00 | America/Anchorage              |
          | (UTC-09:00) America/Juneau                 | -09:00:00 | America/Juneau                 |
          | (UTC-09:00) America/Metlakatla             | -09:00:00 | America/Metlakatla             |
          | (UTC-09:00) America/Nome                   | -09:00:00 | America/Nome                   |
          | (UTC-09:00) America/Sitka                  | -09:00:00 | America/Sitka                  |
          | (UTC-09:00) America/Yakutat                | -09:00:00 | America/Yakutat                |
          | (UTC-09:00) Pacific/Gambier                | -09:00:00 | Pacific/Gambier                |
          | (UTC-08:00) America/Los_Angeles            | -08:00:00 | America/Los_Angeles            |
          | (UTC-08:00) America/Tijuana                | -08:00:00 | America/Tijuana                |
          | (UTC-08:00) America/Vancouver              | -08:00:00 | America/Vancouver              |
          | (UTC-08:00) Pacific/Pitcairn               | -08:00:00 | Pacific/Pitcairn               |
          | (UTC-07:00) America/Boise                  | -07:00:00 | America/Boise                  |
          | (UTC-07:00) America/Cambridge_Bay          | -07:00:00 | America/Cambridge_Bay          |
          | (UTC-07:00) America/Ciudad_Juarez          | -07:00:00 | America/Ciudad_Juarez          |
          | (UTC-07:00) America/Creston                | -07:00:00 | America/Creston                |
          | (UTC-07:00) America/Dawson                 | -07:00:00 | America/Dawson                 |
          | (UTC-07:00) America/Dawson_Creek           | -07:00:00 | America/Dawson_Creek           |
          | (UTC-07:00) America/Denver                 | -07:00:00 | America/Denver                 |
          | (UTC-07:00) America/Edmonton               | -07:00:00 | America/Edmonton               |
          | (UTC-07:00) America/Fort_Nelson            | -07:00:00 | America/Fort_Nelson            |
          | (UTC-07:00) America/Hermosillo             | -07:00:00 | America/Hermosillo             |
          | (UTC-07:00) America/Inuvik                 | -07:00:00 | America/Inuvik                 |
          | (UTC-07:00) America/Mazatlan               | -07:00:00 | America/Mazatlan               |
          | (UTC-07:00) America/Phoenix                | -07:00:00 | America/Phoenix                |
          | (UTC-07:00) America/Whitehorse             | -07:00:00 | America/Whitehorse             |
          | (UTC-06:00) America/Bahia_Banderas         | -06:00:00 | America/Bahia_Banderas         |
          | (UTC-06:00) America/Belize                 | -06:00:00 | America/Belize                 |
          | (UTC-06:00) America/Chicago                | -06:00:00 | America/Chicago                |
          | (UTC-06:00) America/Chihuahua              | -06:00:00 | America/Chihuahua              |
          | (UTC-06:00) America/Costa_Rica             | -06:00:00 | America/Costa_Rica             |
          | (UTC-06:00) America/El_Salvador            | -06:00:00 | America/El_Salvador            |
          | (UTC-06:00) America/Guatemala              | -06:00:00 | America/Guatemala              |
          | (UTC-06:00) America/Indiana/Knox           | -06:00:00 | America/Indiana/Knox           |
          | (UTC-06:00) America/Indiana/Tell_City      | -06:00:00 | America/Indiana/Tell_City      |
          | (UTC-06:00) America/Managua                | -06:00:00 | America/Managua                |
          | (UTC-06:00) America/Matamoros              | -06:00:00 | America/Matamoros              |
          | (UTC-06:00) America/Menominee              | -06:00:00 | America/Menominee              |
          | (UTC-06:00) America/Merida                 | -06:00:00 | America/Merida                 |
          | (UTC-06:00) America/Mexico_City            | -06:00:00 | America/Mexico_City            |
          | (UTC-06:00) America/Monterrey              | -06:00:00 | America/Monterrey              |
          | (UTC-06:00) America/North_Dakota/Beulah    | -06:00:00 | America/North_Dakota/Beulah    |
          | (UTC-06:00) America/North_Dakota/Center    | -06:00:00 | America/North_Dakota/Center    |
          | (UTC-06:00) America/North_Dakota/New_Salem | -06:00:00 | America/North_Dakota/New_Salem |
          | (UTC-06:00) America/Ojinaga                | -06:00:00 | America/Ojinaga                |
          | (UTC-06:00) America/Rankin_Inlet           | -06:00:00 | America/Rankin_Inlet           |
          | (UTC-06:00) America/Regina                 | -06:00:00 | America/Regina                 |
          | (UTC-06:00) America/Resolute               | -06:00:00 | America/Resolute               |
          | (UTC-06:00) America/Swift_Current          | -06:00:00 | America/Swift_Current          |
          | (UTC-06:00) America/Tegucigalpa            | -06:00:00 | America/Tegucigalpa            |
          | (UTC-06:00) America/Winnipeg               | -06:00:00 | America/Winnipeg               |
          | (UTC-06:00) Pacific/Easter                 | -06:00:00 | Pacific/Easter                 |
          | (UTC-06:00) Pacific/Galapagos              | -06:00:00 | Pacific/Galapagos              |
          | (UTC-05:00) America/Atikokan               | -05:00:00 | America/Atikokan               |
          | (UTC-05:00) America/Bogota                 | -05:00:00 | America/Bogota                 |
          | (UTC-05:00) America/Cancun                 | -05:00:00 | America/Cancun                 |
          | (UTC-05:00) America/Cayman                 | -05:00:00 | America/Cayman                 |
          | (UTC-05:00) America/Detroit                | -05:00:00 | America/Detroit                |
          | (UTC-05:00) America/Eirunepe               | -05:00:00 | America/Eirunepe               |
          | (UTC-05:00) America/Grand_Turk             | -05:00:00 | America/Grand_Turk             |
          | (UTC-05:00) America/Guayaquil              | -05:00:00 | America/Guayaquil              |
          | (UTC-05:00) America/Havana                 | -05:00:00 | America/Havana                 |
          | (UTC-05:00) America/Indiana/Indianapolis   | -05:00:00 | America/Indiana/Indianapolis   |
          | (UTC-05:00) America/Indiana/Marengo        | -05:00:00 | America/Indiana/Marengo        |
          | (UTC-05:00) America/Indiana/Petersburg     | -05:00:00 | America/Indiana/Petersburg     |
          | (UTC-05:00) America/Indiana/Vevay          | -05:00:00 | America/Indiana/Vevay          |
          | (UTC-05:00) America/Indiana/Vincennes      | -05:00:00 | America/Indiana/Vincennes      |
          | (UTC-05:00) America/Indiana/Winamac        | -05:00:00 | America/Indiana/Winamac        |
          | (UTC-05:00) America/Iqaluit                | -05:00:00 | America/Iqaluit                |
          | (UTC-05:00) America/Jamaica                | -05:00:00 | America/Jamaica                |
          | (UTC-05:00) America/Kentucky/Louisville    | -05:00:00 | America/Kentucky/Louisville    |
          | (UTC-05:00) America/Kentucky/Monticello    | -05:00:00 | America/Kentucky/Monticello    |
          | (UTC-05:00) America/Lima                   | -05:00:00 | America/Lima                   |
          | (UTC-05:00) America/Nassau                 | -05:00:00 | America/Nassau                 |
          | (UTC-05:00) America/New_York               | -05:00:00 | America/New_York               |
          | (UTC-05:00) America/Panama                 | -05:00:00 | America/Panama                 |
          | (UTC-05:00) America/Port-au-Prince         | -05:00:00 | America/Port-au-Prince         |
          | (UTC-05:00) America/Rio_Branco             | -05:00:00 | America/Rio_Branco             |
          | (UTC-05:00) America/Toronto                | -05:00:00 | America/Toronto                |
          | (UTC-04:00) America/Anguilla               | -04:00:00 | America/Anguilla               |
          | (UTC-04:00) America/Antigua                | -04:00:00 | America/Antigua                |
          | (UTC-04:00) America/Aruba                  | -04:00:00 | America/Aruba                  |
          | (UTC-04:00) America/Barbados               | -04:00:00 | America/Barbados               |
          | (UTC-04:00) America/Blanc-Sablon           | -04:00:00 | America/Blanc-Sablon           |
          | (UTC-04:00) America/Boa_Vista              | -04:00:00 | America/Boa_Vista              |
          | (UTC-04:00) America/Campo_Grande           | -04:00:00 | America/Campo_Grande           |
          | (UTC-04:00) America/Caracas                | -04:00:00 | America/Caracas                |
          | (UTC-04:00) America/Cuiaba                 | -04:00:00 | America/Cuiaba                 |
          | (UTC-04:00) America/Curacao                | -04:00:00 | America/Curacao                |
          | (UTC-04:00) America/Dominica               | -04:00:00 | America/Dominica               |
          | (UTC-04:00) America/Glace_Bay              | -04:00:00 | America/Glace_Bay              |
          | (UTC-04:00) America/Goose_Bay              | -04:00:00 | America/Goose_Bay              |
          | (UTC-04:00) America/Grenada                | -04:00:00 | America/Grenada                |
          | (UTC-04:00) America/Guadeloupe             | -04:00:00 | America/Guadeloupe             |
          | (UTC-04:00) America/Guyana                 | -04:00:00 | America/Guyana                 |
          | (UTC-04:00) America/Halifax                | -04:00:00 | America/Halifax                |
          | (UTC-04:00) America/Kralendijk             | -04:00:00 | America/Kralendijk             |
          | (UTC-04:00) America/La_Paz                 | -04:00:00 | America/La_Paz                 |
          | (UTC-04:00) America/Lower_Princes          | -04:00:00 | America/Lower_Princes          |
          | (UTC-04:00) America/Manaus                 | -04:00:00 | America/Manaus                 |
          | (UTC-04:00) America/Marigot                | -04:00:00 | America/Marigot                |
          | (UTC-04:00) America/Martinique             | -04:00:00 | America/Martinique             |
          | (UTC-04:00) America/Moncton                | -04:00:00 | America/Moncton                |
          | (UTC-04:00) America/Montserrat             | -04:00:00 | America/Montserrat             |
          | (UTC-04:00) America/Port_of_Spain          | -04:00:00 | America/Port_of_Spain          |
          | (UTC-04:00) America/Porto_Velho            | -04:00:00 | America/Porto_Velho            |
          | (UTC-04:00) America/Puerto_Rico            | -04:00:00 | America/Puerto_Rico            |
          | (UTC-04:00) America/Santiago               | -04:00:00 | America/Santiago               |
          | (UTC-04:00) America/Santo_Domingo          | -04:00:00 | America/Santo_Domingo          |
          | (UTC-04:00) America/St_Barthelemy          | -04:00:00 | America/St_Barthelemy          |
          | (UTC-04:00) America/St_Kitts               | -04:00:00 | America/St_Kitts               |
          | (UTC-04:00) America/St_Lucia               | -04:00:00 | America/St_Lucia               |
          | (UTC-04:00) America/St_Thomas              | -04:00:00 | America/St_Thomas              |
          | (UTC-04:00) America/St_Vincent             | -04:00:00 | America/St_Vincent             |
          | (UTC-04:00) America/Thule                  | -04:00:00 | America/Thule                  |
          | (UTC-04:00) America/Tortola                | -04:00:00 | America/Tortola                |
          | (UTC-04:00) Atlantic/Bermuda               | -04:00:00 | Atlantic/Bermuda               |
          | (UTC-03:30) America/St_Johns               | -03:30:00 | America/St_Johns               |
          | (UTC-03:00) America/Araguaina              | -03:00:00 | America/Araguaina              |
          | (UTC-03:00) America/Argentina/Buenos_Aires | -03:00:00 | America/Argentina/Buenos_Aires |
          | (UTC-03:00) America/Argentina/Catamarca    | -03:00:00 | America/Argentina/Catamarca    |
          | (UTC-03:00) America/Argentina/Cordoba      | -03:00:00 | America/Argentina/Cordoba      |
          | (UTC-03:00) America/Argentina/Jujuy        | -03:00:00 | America/Argentina/Jujuy        |
          | (UTC-03:00) America/Argentina/La_Rioja     | -03:00:00 | America/Argentina/La_Rioja     |
          | (UTC-03:00) America/Argentina/Mendoza      | -03:00:00 | America/Argentina/Mendoza      |
          | (UTC-03:00) America/Argentina/Rio_Gallegos | -03:00:00 | America/Argentina/Rio_Gallegos |
          | (UTC-03:00) America/Argentina/Salta        | -03:00:00 | America/Argentina/Salta        |
          | (UTC-03:00) America/Argentina/San_Juan     | -03:00:00 | America/Argentina/San_Juan     |
          | (UTC-03:00) America/Argentina/San_Luis     | -03:00:00 | America/Argentina/San_Luis     |
          | (UTC-03:00) America/Argentina/Tucuman      | -03:00:00 | America/Argentina/Tucuman      |
          | (UTC-03:00) America/Argentina/Ushuaia      | -03:00:00 | America/Argentina/Ushuaia      |
          | (UTC-03:00) America/Asuncion               | -03:00:00 | America/Asuncion               |
          | (UTC-03:00) America/Bahia                  | -03:00:00 | America/Bahia                  |
          | (UTC-03:00) America/Belem                  | -03:00:00 | America/Belem                  |
          | (UTC-03:00) America/Cayenne                | -03:00:00 | America/Cayenne                |
          | (UTC-03:00) America/Coyhaique              | -03:00:00 | America/Coyhaique              |
          | (UTC-03:00) America/Fortaleza              | -03:00:00 | America/Fortaleza              |
          | (UTC-03:00) America/Maceio                 | -03:00:00 | America/Maceio                 |
          | (UTC-03:00) America/Miquelon               | -03:00:00 | America/Miquelon               |
          | (UTC-03:00) America/Montevideo             | -03:00:00 | America/Montevideo             |
          | (UTC-03:00) America/Paramaribo             | -03:00:00 | America/Paramaribo             |
          | (UTC-03:00) America/Punta_Arenas           | -03:00:00 | America/Punta_Arenas           |
          | (UTC-03:00) America/Recife                 | -03:00:00 | America/Recife                 |
          | (UTC-03:00) America/Santarem               | -03:00:00 | America/Santarem               |
          | (UTC-03:00) America/Sao_Paulo              | -03:00:00 | America/Sao_Paulo              |
          | (UTC-03:00) Antarctica/Palmer              | -03:00:00 | Antarctica/Palmer              |
          | (UTC-03:00) Antarctica/Rothera             | -03:00:00 | Antarctica/Rothera             |
          | (UTC-03:00) Atlantic/Stanley               | -03:00:00 | Atlantic/Stanley               |
          | (UTC-02:00) America/Noronha                | -02:00:00 | America/Noronha                |
          | (UTC-02:00) America/Nuuk                   | -02:00:00 | America/Nuuk                   |
          | (UTC-02:00) America/Scoresbysund           | -02:00:00 | America/Scoresbysund           |
          | (UTC-02:00) Atlantic/South_Georgia         | -02:00:00 | Atlantic/South_Georgia         |
          | (UTC-01:00) Atlantic/Azores                | -01:00:00 | Atlantic/Azores                |
          | (UTC-01:00) Atlantic/Cape_Verde            | -01:00:00 | Atlantic/Cape_Verde            |
          | (UTC) Coordinated Universal Time           | 00:00:00  | UTC                            |
          | (UTC+00:00) Africa/Abidjan                 | 00:00:00  | Africa/Abidjan                 |
          | (UTC+00:00) Africa/Accra                   | 00:00:00  | Africa/Accra                   |
          | (UTC+00:00) Africa/Bamako                  | 00:00:00  | Africa/Bamako                  |
          | (UTC+00:00) Africa/Banjul                  | 00:00:00  | Africa/Banjul                  |
          | (UTC+00:00) Africa/Bissau                  | 00:00:00  | Africa/Bissau                  |
          | (UTC+00:00) Africa/Casablanca              | 00:00:00  | Africa/Casablanca              |
          | (UTC+00:00) Africa/Conakry                 | 00:00:00  | Africa/Conakry                 |
          | (UTC+00:00) Africa/Dakar                   | 00:00:00  | Africa/Dakar                   |
          | (UTC+00:00) Africa/El_Aaiun                | 00:00:00  | Africa/El_Aaiun                |
          | (UTC+00:00) Africa/Freetown                | 00:00:00  | Africa/Freetown                |
          | (UTC+00:00) Africa/Lome                    | 00:00:00  | Africa/Lome                    |
          | (UTC+00:00) Africa/Monrovia                | 00:00:00  | Africa/Monrovia                |
          | (UTC+00:00) Africa/Nouakchott              | 00:00:00  | Africa/Nouakchott              |
          | (UTC+00:00) Africa/Ouagadougou             | 00:00:00  | Africa/Ouagadougou             |
          | (UTC+00:00) Africa/Sao_Tome                | 00:00:00  | Africa/Sao_Tome                |
          | (UTC+00:00) America/Danmarkshavn           | 00:00:00  | America/Danmarkshavn           |
          | (UTC+00:00) Antarctica/Troll               | 00:00:00  | Antarctica/Troll               |
          | (UTC+00:00) Atlantic/Canary                | 00:00:00  | Atlantic/Canary                |
          | (UTC+00:00) Atlantic/Faroe                 | 00:00:00  | Atlantic/Faroe                 |
          | (UTC+00:00) Atlantic/Madeira               | 00:00:00  | Atlantic/Madeira               |
          | (UTC+00:00) Atlantic/Reykjavik             | 00:00:00  | Atlantic/Reykjavik             |
          | (UTC+00:00) Atlantic/St_Helena             | 00:00:00  | Atlantic/St_Helena             |
          | (UTC+00:00) Europe/Dublin                  | 00:00:00  | Europe/Dublin                  |
          | (UTC+00:00) Europe/Guernsey                | 00:00:00  | Europe/Guernsey                |
          | (UTC+00:00) Europe/Isle_of_Man             | 00:00:00  | Europe/Isle_of_Man             |
          | (UTC+00:00) Europe/Jersey                  | 00:00:00  | Europe/Jersey                  |
          | (UTC+00:00) Europe/Lisbon                  | 00:00:00  | Europe/Lisbon                  |
          | (UTC+00:00) Europe/London                  | 00:00:00  | Europe/London                  |
          | (UTC+01:00) Africa/Algiers                 | 01:00:00  | Africa/Algiers                 |
          | (UTC+01:00) Africa/Bangui                  | 01:00:00  | Africa/Bangui                  |
          | (UTC+01:00) Africa/Brazzaville             | 01:00:00  | Africa/Brazzaville             |
          | (UTC+01:00) Africa/Ceuta                   | 01:00:00  | Africa/Ceuta                   |
          | (UTC+01:00) Africa/Douala                  | 01:00:00  | Africa/Douala                  |
          | (UTC+01:00) Africa/Kinshasa                | 01:00:00  | Africa/Kinshasa                |
          | (UTC+01:00) Africa/Lagos                   | 01:00:00  | Africa/Lagos                   |
          | (UTC+01:00) Africa/Libreville              | 01:00:00  | Africa/Libreville              |
          | (UTC+01:00) Africa/Luanda                  | 01:00:00  | Africa/Luanda                  |
          | (UTC+01:00) Africa/Malabo                  | 01:00:00  | Africa/Malabo                  |
          | (UTC+01:00) Africa/Ndjamena                | 01:00:00  | Africa/Ndjamena                |
          | (UTC+01:00) Africa/Niamey                  | 01:00:00  | Africa/Niamey                  |
          | (UTC+01:00) Africa/Porto-Novo              | 01:00:00  | Africa/Porto-Novo              |
          | (UTC+01:00) Africa/Tunis                   | 01:00:00  | Africa/Tunis                   |
          | (UTC+01:00) Arctic/Longyearbyen            | 01:00:00  | Arctic/Longyearbyen            |
          | (UTC+01:00) Europe/Amsterdam               | 01:00:00  | Europe/Amsterdam               |
          | (UTC+01:00) Europe/Andorra                 | 01:00:00  | Europe/Andorra                 |
          | (UTC+01:00) Europe/Belgrade                | 01:00:00  | Europe/Belgrade                |
          | (UTC+01:00) Europe/Berlin                  | 01:00:00  | Europe/Berlin                  |
          | (UTC+01:00) Europe/Bratislava              | 01:00:00  | Europe/Bratislava              |
          | (UTC+01:00) Europe/Brussels                | 01:00:00  | Europe/Brussels                |
          | (UTC+01:00) Europe/Budapest                | 01:00:00  | Europe/Budapest                |
          | (UTC+01:00) Europe/Busingen                | 01:00:00  | Europe/Busingen                |
          | (UTC+01:00) Europe/Copenhagen              | 01:00:00  | Europe/Copenhagen              |
          | (UTC+01:00) Europe/Gibraltar               | 01:00:00  | Europe/Gibraltar               |
          | (UTC+01:00) Europe/Ljubljana               | 01:00:00  | Europe/Ljubljana               |
          | (UTC+01:00) Europe/Luxembourg              | 01:00:00  | Europe/Luxembourg              |
          | (UTC+01:00) Europe/Madrid                  | 01:00:00  | Europe/Madrid                  |
          | (UTC+01:00) Europe/Malta                   | 01:00:00  | Europe/Malta                   |
          | (UTC+01:00) Europe/Monaco                  | 01:00:00  | Europe/Monaco                  |
          | (UTC+01:00) Europe/Oslo                    | 01:00:00  | Europe/Oslo                    |
          | (UTC+01:00) Europe/Paris                   | 01:00:00  | Europe/Paris                   |
          | (UTC+01:00) Europe/Podgorica               | 01:00:00  | Europe/Podgorica               |
          | (UTC+01:00) Europe/Prague                  | 01:00:00  | Europe/Prague                  |
          | (UTC+01:00) Europe/Rome                    | 01:00:00  | Europe/Rome                    |
          | (UTC+01:00) Europe/San_Marino              | 01:00:00  | Europe/San_Marino              |
          | (UTC+01:00) Europe/Sarajevo                | 01:00:00  | Europe/Sarajevo                |
          | (UTC+01:00) Europe/Skopje                  | 01:00:00  | Europe/Skopje                  |
          | (UTC+01:00) Europe/Stockholm               | 01:00:00  | Europe/Stockholm               |
          | (UTC+01:00) Europe/Tirane                  | 01:00:00  | Europe/Tirane                  |
          | (UTC+01:00) Europe/Vaduz                   | 01:00:00  | Europe/Vaduz                   |
          | (UTC+01:00) Europe/Vatican                 | 01:00:00  | Europe/Vatican                 |
          | (UTC+01:00) Europe/Vienna                  | 01:00:00  | Europe/Vienna                  |
          | (UTC+01:00) Europe/Warsaw                  | 01:00:00  | Europe/Warsaw                  |
          | (UTC+01:00) Europe/Zagreb                  | 01:00:00  | Europe/Zagreb                  |
          | (UTC+01:00) Europe/Zurich                  | 01:00:00  | Europe/Zurich                  |
          | (UTC+02:00) Africa/Blantyre                | 02:00:00  | Africa/Blantyre                |
          | (UTC+02:00) Africa/Bujumbura               | 02:00:00  | Africa/Bujumbura               |
          | (UTC+02:00) Africa/Cairo                   | 02:00:00  | Africa/Cairo                   |
          | (UTC+02:00) Africa/Gaborone                | 02:00:00  | Africa/Gaborone                |
          | (UTC+02:00) Africa/Harare                  | 02:00:00  | Africa/Harare                  |
          | (UTC+02:00) Africa/Johannesburg            | 02:00:00  | Africa/Johannesburg            |
          | (UTC+02:00) Africa/Juba                    | 02:00:00  | Africa/Juba                    |
          | (UTC+02:00) Africa/Khartoum                | 02:00:00  | Africa/Khartoum                |
          | (UTC+02:00) Africa/Kigali                  | 02:00:00  | Africa/Kigali                  |
          | (UTC+02:00) Africa/Lubumbashi              | 02:00:00  | Africa/Lubumbashi              |
          | (UTC+02:00) Africa/Lusaka                  | 02:00:00  | Africa/Lusaka                  |
          | (UTC+02:00) Africa/Maputo                  | 02:00:00  | Africa/Maputo                  |
          | (UTC+02:00) Africa/Maseru                  | 02:00:00  | Africa/Maseru                  |
          | (UTC+02:00) Africa/Mbabane                 | 02:00:00  | Africa/Mbabane                 |
          | (UTC+02:00) Africa/Tripoli                 | 02:00:00  | Africa/Tripoli                 |
          | (UTC+02:00) Africa/Windhoek                | 02:00:00  | Africa/Windhoek                |
          | (UTC+02:00) Asia/Beirut                    | 02:00:00  | Asia/Beirut                    |
          | (UTC+02:00) Asia/Famagusta                 | 02:00:00  | Asia/Famagusta                 |
          | (UTC+02:00) Asia/Gaza                      | 02:00:00  | Asia/Gaza                      |
          | (UTC+02:00) Asia/Hebron                    | 02:00:00  | Asia/Hebron                    |
          | (UTC+02:00) Asia/Jerusalem                 | 02:00:00  | Asia/Jerusalem                 |
          | (UTC+02:00) Asia/Nicosia                   | 02:00:00  | Asia/Nicosia                   |
          | (UTC+02:00) Europe/Athens                  | 02:00:00  | Europe/Athens                  |
          | (UTC+02:00) Europe/Bucharest               | 02:00:00  | Europe/Bucharest               |
          | (UTC+02:00) Europe/Chisinau                | 02:00:00  | Europe/Chisinau                |
          | (UTC+02:00) Europe/Helsinki                | 02:00:00  | Europe/Helsinki                |
          | (UTC+02:00) Europe/Kaliningrad             | 02:00:00  | Europe/Kaliningrad             |
          | (UTC+02:00) Europe/Kyiv                    | 02:00:00  | Europe/Kyiv                    |
          | (UTC+02:00) Europe/Mariehamn               | 02:00:00  | Europe/Mariehamn               |
          | (UTC+02:00) Europe/Riga                    | 02:00:00  | Europe/Riga                    |
          | (UTC+02:00) Europe/Sofia                   | 02:00:00  | Europe/Sofia                   |
          | (UTC+02:00) Europe/Tallinn                 | 02:00:00  | Europe/Tallinn                 |
          | (UTC+02:00) Europe/Vilnius                 | 02:00:00  | Europe/Vilnius                 |
          | (UTC+03:00) Africa/Addis_Ababa             | 03:00:00  | Africa/Addis_Ababa             |
          | (UTC+03:00) Africa/Asmara                  | 03:00:00  | Africa/Asmara                  |
          | (UTC+03:00) Africa/Dar_es_Salaam           | 03:00:00  | Africa/Dar_es_Salaam           |
          | (UTC+03:00) Africa/Djibouti                | 03:00:00  | Africa/Djibouti                |
          | (UTC+03:00) Africa/Kampala                 | 03:00:00  | Africa/Kampala                 |
          | (UTC+03:00) Africa/Mogadishu               | 03:00:00  | Africa/Mogadishu               |
          | (UTC+03:00) Africa/Nairobi                 | 03:00:00  | Africa/Nairobi                 |
          | (UTC+03:00) Antarctica/Syowa               | 03:00:00  | Antarctica/Syowa               |
          | (UTC+03:00) Asia/Aden                      | 03:00:00  | Asia/Aden                      |
          | (UTC+03:00) Asia/Amman                     | 03:00:00  | Asia/Amman                     |
          | (UTC+03:00) Asia/Baghdad                   | 03:00:00  | Asia/Baghdad                   |
          | (UTC+03:00) Asia/Bahrain                   | 03:00:00  | Asia/Bahrain                   |
          | (UTC+03:00) Asia/Damascus                  | 03:00:00  | Asia/Damascus                  |
          | (UTC+03:00) Asia/Kuwait                    | 03:00:00  | Asia/Kuwait                    |
          | (UTC+03:00) Asia/Qatar                     | 03:00:00  | Asia/Qatar                     |
          | (UTC+03:00) Asia/Riyadh                    | 03:00:00  | Asia/Riyadh                    |
          | (UTC+03:00) Europe/Istanbul                | 03:00:00  | Europe/Istanbul                |
          | (UTC+03:00) Europe/Kirov                   | 03:00:00  | Europe/Kirov                   |
          | (UTC+03:00) Europe/Minsk                   | 03:00:00  | Europe/Minsk                   |
          | (UTC+03:00) Europe/Moscow                  | 03:00:00  | Europe/Moscow                  |
          | (UTC+03:00) Europe/Simferopol              | 03:00:00  | Europe/Simferopol              |
          | (UTC+03:00) Europe/Volgograd               | 03:00:00  | Europe/Volgograd               |
          | (UTC+03:00) Indian/Antananarivo            | 03:00:00  | Indian/Antananarivo            |
          | (UTC+03:00) Indian/Comoro                  | 03:00:00  | Indian/Comoro                  |
          | (UTC+03:00) Indian/Mayotte                 | 03:00:00  | Indian/Mayotte                 |
          | (UTC+03:30) Asia/Tehran                    | 03:30:00  | Asia/Tehran                    |
          | (UTC+04:00) Asia/Baku                      | 04:00:00  | Asia/Baku                      |
          | (UTC+04:00) Asia/Dubai                     | 04:00:00  | Asia/Dubai                     |
          | (UTC+04:00) Asia/Muscat                    | 04:00:00  | Asia/Muscat                    |
          | (UTC+04:00) Asia/Tbilisi                   | 04:00:00  | Asia/Tbilisi                   |
          | (UTC+04:00) Asia/Yerevan                   | 04:00:00  | Asia/Yerevan                   |
          | (UTC+04:00) Europe/Astrakhan               | 04:00:00  | Europe/Astrakhan               |
          | (UTC+04:00) Europe/Samara                  | 04:00:00  | Europe/Samara                  |
          | (UTC+04:00) Europe/Saratov                 | 04:00:00  | Europe/Saratov                 |
          | (UTC+04:00) Europe/Ulyanovsk               | 04:00:00  | Europe/Ulyanovsk               |
          | (UTC+04:00) Indian/Mahe                    | 04:00:00  | Indian/Mahe                    |
          | (UTC+04:00) Indian/Mauritius               | 04:00:00  | Indian/Mauritius               |
          | (UTC+04:00) Indian/Reunion                 | 04:00:00  | Indian/Reunion                 |
          | (UTC+04:30) Asia/Kabul                     | 04:30:00  | Asia/Kabul                     |
          | (UTC+05:00) Antarctica/Mawson              | 05:00:00  | Antarctica/Mawson              |
          | (UTC+05:00) Antarctica/Vostok              | 05:00:00  | Antarctica/Vostok              |
          | (UTC+05:00) Asia/Almaty                    | 05:00:00  | Asia/Almaty                    |
          | (UTC+05:00) Asia/Aqtau                     | 05:00:00  | Asia/Aqtau                     |
          | (UTC+05:00) Asia/Aqtobe                    | 05:00:00  | Asia/Aqtobe                    |
          | (UTC+05:00) Asia/Ashgabat                  | 05:00:00  | Asia/Ashgabat                  |
          | (UTC+05:00) Asia/Atyrau                    | 05:00:00  | Asia/Atyrau                    |
          | (UTC+05:00) Asia/Dushanbe                  | 05:00:00  | Asia/Dushanbe                  |
          | (UTC+05:00) Asia/Karachi                   | 05:00:00  | Asia/Karachi                   |
          | (UTC+05:00) Asia/Oral                      | 05:00:00  | Asia/Oral                      |
          | (UTC+05:00) Asia/Qostanay                  | 05:00:00  | Asia/Qostanay                  |
          | (UTC+05:00) Asia/Qyzylorda                 | 05:00:00  | Asia/Qyzylorda                 |
          | (UTC+05:00) Asia/Samarkand                 | 05:00:00  | Asia/Samarkand                 |
          | (UTC+05:00) Asia/Tashkent                  | 05:00:00  | Asia/Tashkent                  |
          | (UTC+05:00) Asia/Yekaterinburg             | 05:00:00  | Asia/Yekaterinburg             |
          | (UTC+05:00) Indian/Kerguelen               | 05:00:00  | Indian/Kerguelen               |
          | (UTC+05:00) Indian/Maldives                | 05:00:00  | Indian/Maldives                |
          | (UTC+05:30) Asia/Colombo                   | 05:30:00  | Asia/Colombo                   |
          | (UTC+05:30) Asia/Kolkata                   | 05:30:00  | Asia/Kolkata                   |
          | (UTC+05:45) Asia/Kathmandu                 | 05:45:00  | Asia/Kathmandu                 |
          | (UTC+06:00) Asia/Bishkek                   | 06:00:00  | Asia/Bishkek                   |
          | (UTC+06:00) Asia/Dhaka                     | 06:00:00  | Asia/Dhaka                     |
          | (UTC+06:00) Asia/Omsk                      | 06:00:00  | Asia/Omsk                      |
          | (UTC+06:00) Asia/Thimphu                   | 06:00:00  | Asia/Thimphu                   |
          | (UTC+06:00) Asia/Urumqi                    | 06:00:00  | Asia/Urumqi                    |
          | (UTC+06:00) Indian/Chagos                  | 06:00:00  | Indian/Chagos                  |
          | (UTC+06:30) Asia/Yangon                    | 06:30:00  | Asia/Yangon                    |
          | (UTC+06:30) Indian/Cocos                   | 06:30:00  | Indian/Cocos                   |
          | (UTC+07:00) Antarctica/Davis               | 07:00:00  | Antarctica/Davis               |
          | (UTC+07:00) Asia/Bangkok                   | 07:00:00  | Asia/Bangkok                   |
          | (UTC+07:00) Asia/Barnaul                   | 07:00:00  | Asia/Barnaul                   |
          | (UTC+07:00) Asia/Ho_Chi_Minh               | 07:00:00  | Asia/Ho_Chi_Minh               |
          | (UTC+07:00) Asia/Hovd                      | 07:00:00  | Asia/Hovd                      |
          | (UTC+07:00) Asia/Jakarta                   | 07:00:00  | Asia/Jakarta                   |
          | (UTC+07:00) Asia/Krasnoyarsk               | 07:00:00  | Asia/Krasnoyarsk               |
          | (UTC+07:00) Asia/Novokuznetsk              | 07:00:00  | Asia/Novokuznetsk              |
          | (UTC+07:00) Asia/Novosibirsk               | 07:00:00  | Asia/Novosibirsk               |
          | (UTC+07:00) Asia/Phnom_Penh                | 07:00:00  | Asia/Phnom_Penh                |
          | (UTC+07:00) Asia/Pontianak                 | 07:00:00  | Asia/Pontianak                 |
          | (UTC+07:00) Asia/Tomsk                     | 07:00:00  | Asia/Tomsk                     |
          | (UTC+07:00) Asia/Vientiane                 | 07:00:00  | Asia/Vientiane                 |
          | (UTC+07:00) Indian/Christmas               | 07:00:00  | Indian/Christmas               |
          | (UTC+08:00) Antarctica/Casey               | 08:00:00  | Antarctica/Casey               |
          | (UTC+08:00) Asia/Brunei                    | 08:00:00  | Asia/Brunei                    |
          | (UTC+08:00) Asia/Hong_Kong                 | 08:00:00  | Asia/Hong_Kong                 |
          | (UTC+08:00) Asia/Irkutsk                   | 08:00:00  | Asia/Irkutsk                   |
          | (UTC+08:00) Asia/Kuala_Lumpur              | 08:00:00  | Asia/Kuala_Lumpur              |
          | (UTC+08:00) Asia/Kuching                   | 08:00:00  | Asia/Kuching                   |
          | (UTC+08:00) Asia/Macau                     | 08:00:00  | Asia/Macau                     |
          | (UTC+08:00) Asia/Makassar                  | 08:00:00  | Asia/Makassar                  |
          | (UTC+08:00) Asia/Manila                    | 08:00:00  | Asia/Manila                    |
          | (UTC+08:00) Asia/Shanghai                  | 08:00:00  | Asia/Shanghai                  |
          | (UTC+08:00) Asia/Singapore                 | 08:00:00  | Asia/Singapore                 |
          | (UTC+08:00) Asia/Taipei                    | 08:00:00  | Asia/Taipei                    |
          | (UTC+08:00) Asia/Ulaanbaatar               | 08:00:00  | Asia/Ulaanbaatar               |
          | (UTC+08:00) Australia/Perth                | 08:00:00  | Australia/Perth                |
          | (UTC+08:45) Australia/Eucla                | 08:45:00  | Australia/Eucla                |
          | (UTC+09:00) Asia/Chita                     | 09:00:00  | Asia/Chita                     |
          | (UTC+09:00) Asia/Dili                      | 09:00:00  | Asia/Dili                      |
          | (UTC+09:00) Asia/Jayapura                  | 09:00:00  | Asia/Jayapura                  |
          | (UTC+09:00) Asia/Khandyga                  | 09:00:00  | Asia/Khandyga                  |
          | (UTC+09:00) Asia/Pyongyang                 | 09:00:00  | Asia/Pyongyang                 |
          | (UTC+09:00) Asia/Seoul                     | 09:00:00  | Asia/Seoul                     |
          | (UTC+09:00) Asia/Tokyo                     | 09:00:00  | Asia/Tokyo                     |
          | (UTC+09:00) Asia/Yakutsk                   | 09:00:00  | Asia/Yakutsk                   |
          | (UTC+09:00) Pacific/Palau                  | 09:00:00  | Pacific/Palau                  |
          | (UTC+09:30) Australia/Adelaide             | 09:30:00  | Australia/Adelaide             |
          | (UTC+09:30) Australia/Broken_Hill          | 09:30:00  | Australia/Broken_Hill          |
          | (UTC+09:30) Australia/Darwin               | 09:30:00  | Australia/Darwin               |
          | (UTC+10:00) Antarctica/DumontDUrville      | 10:00:00  | Antarctica/DumontDUrville      |
          | (UTC+10:00) Antarctica/Macquarie           | 10:00:00  | Antarctica/Macquarie           |
          | (UTC+10:00) Asia/Ust-Nera                  | 10:00:00  | Asia/Ust-Nera                  |
          | (UTC+10:00) Asia/Vladivostok               | 10:00:00  | Asia/Vladivostok               |
          | (UTC+10:00) Australia/Brisbane             | 10:00:00  | Australia/Brisbane             |
          | (UTC+10:00) Australia/Hobart               | 10:00:00  | Australia/Hobart               |
          | (UTC+10:00) Australia/Lindeman             | 10:00:00  | Australia/Lindeman             |
          | (UTC+10:00) Australia/Melbourne            | 10:00:00  | Australia/Melbourne            |
          | (UTC+10:00) Australia/Sydney               | 10:00:00  | Australia/Sydney               |
          | (UTC+10:00) Pacific/Chuuk                  | 10:00:00  | Pacific/Chuuk                  |
          | (UTC+10:00) Pacific/Guam                   | 10:00:00  | Pacific/Guam                   |
          | (UTC+10:00) Pacific/Port_Moresby           | 10:00:00  | Pacific/Port_Moresby           |
          | (UTC+10:00) Pacific/Saipan                 | 10:00:00  | Pacific/Saipan                 |
          | (UTC+10:30) Australia/Lord_Howe            | 10:30:00  | Australia/Lord_Howe            |
          | (UTC+11:00) Asia/Magadan                   | 11:00:00  | Asia/Magadan                   |
          | (UTC+11:00) Asia/Sakhalin                  | 11:00:00  | Asia/Sakhalin                  |
          | (UTC+11:00) Asia/Srednekolymsk             | 11:00:00  | Asia/Srednekolymsk             |
          | (UTC+11:00) Pacific/Bougainville           | 11:00:00  | Pacific/Bougainville           |
          | (UTC+11:00) Pacific/Efate                  | 11:00:00  | Pacific/Efate                  |
          | (UTC+11:00) Pacific/Guadalcanal            | 11:00:00  | Pacific/Guadalcanal            |
          | (UTC+11:00) Pacific/Kosrae                 | 11:00:00  | Pacific/Kosrae                 |
          | (UTC+11:00) Pacific/Norfolk                | 11:00:00  | Pacific/Norfolk                |
          | (UTC+11:00) Pacific/Noumea                 | 11:00:00  | Pacific/Noumea                 |
          | (UTC+11:00) Pacific/Pohnpei                | 11:00:00  | Pacific/Pohnpei                |
          | (UTC+12:00) Antarctica/McMurdo             | 12:00:00  | Antarctica/McMurdo             |
          | (UTC+12:00) Asia/Anadyr                    | 12:00:00  | Asia/Anadyr                    |
          | (UTC+12:00) Asia/Kamchatka                 | 12:00:00  | Asia/Kamchatka                 |
          | (UTC+12:00) Pacific/Auckland               | 12:00:00  | Pacific/Auckland               |
          | (UTC+12:00) Pacific/Fiji                   | 12:00:00  | Pacific/Fiji                   |
          | (UTC+12:00) Pacific/Funafuti               | 12:00:00  | Pacific/Funafuti               |
          | (UTC+12:00) Pacific/Kwajalein              | 12:00:00  | Pacific/Kwajalein              |
          | (UTC+12:00) Pacific/Majuro                 | 12:00:00  | Pacific/Majuro                 |
          | (UTC+12:00) Pacific/Nauru                  | 12:00:00  | Pacific/Nauru                  |
          | (UTC+12:00) Pacific/Tarawa                 | 12:00:00  | Pacific/Tarawa                 |
          | (UTC+12:00) Pacific/Wake                   | 12:00:00  | Pacific/Wake                   |
          | (UTC+12:00) Pacific/Wallis                 | 12:00:00  | Pacific/Wallis                 |
          | (UTC+12:45) Pacific/Chatham                | 12:45:00  | Pacific/Chatham                |
          | (UTC+13:00) Pacific/Apia                   | 13:00:00  | Pacific/Apia                   |
          | (UTC+13:00) Pacific/Fakaofo                | 13:00:00  | Pacific/Fakaofo                |
          | (UTC+13:00) Pacific/Kanton                 | 13:00:00  | Pacific/Kanton                 |
          | (UTC+13:00) Pacific/Tongatapu              | 13:00:00  | Pacific/Tongatapu              |
          | (UTC+14:00) Pacific/Kiritimati             | 14:00:00  | Pacific/Kiritimati             |
